### DISCUSSION TITLE
Are deleted files removed?

### DISCUSSION THREAD

**Discussion by cheerfuloriole** [wpengine/github-action-wpe-site-deploy#52] [Q&A]
Hello! Curious, after removing or renaming a file, will the action remove the remnants from WP Engine?

**Comment by roryashfordbentley** [comment]
Hey! 

I came across this yesterday, if you use the `--delete` flag, files removed in your repository will also be removed from WP Engine.

Here is an example of how we use the delete flag in our workflow deployment:

```
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: GitHub Action Deploy to WP Engine
              uses: wpengine/github-action-wpe-site-deploy@v3
              with:
                  WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
                  # this is the staging ENVNAME.wpengine.com
                  WPE_ENV: ADD THE WPE ENV NAME HERE
                  SRC_PATH: "wp-content/"
                  REMOTE_PATH: "wp-content/"
                  FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=wp-content/wpe-config/deployment-exclude.txt
                  SCRIPT: "wp-content/wpe-config/postdeploy.sh"

```
