### DISCUSSION TITLE
How to only commit modified, new, or deleted files?

### DISCUSSION THREAD

**Discussion by JStantonWordPress** [wpengine/github-action-wpe-site-deploy#74] [Q&A]
It appears on every deployment it pushes ALL the files in the repository which takes 3-4 minutes. Is there anyway to only push files that has been modified, newly added, or deleted? Essentially the contents of that commit. Any help would be greatly appreciated. Here is my current .yaml file

`name: Deploy to WP Engine
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: bbp2023
          # Deploy Options
          REMOTE_PATH: "wp-content/"
          PHP_LINT: FALSE
          CACHE_CLEAR: TRUE`

**Comment by jacksonwp** [comment]
@JStantonWordPress - this was driving me crazy, and finally got to the bottom of it.

Git checkout does not set the file modification times (by design) - which in turn causes rsync to treat every file as new and needing to be deployed.

The fix is simple - modify your checkout to use `fetch-depth: 0` and then add the Restore Timestamps action after checkout and before wpe-site-deploy.

```
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Restore Timestamps
        uses: chetan/git-restore-mtime-action@v1
```

Adding `fetch-depth` will checkout the entire commit history, which `git-restore-mtime-action` will in turn use to correctly set the file modification times - enabling rsync to skip 1,000s of files.

This has saved up 3-4 minutes per deploy on average in our workflows.

**Reply by JStantonWordPress** [reply]
@jacksonwp thanks!

Does this look correct?

name: Deploy to WP Engine
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      **- name: Restore Timestamps
         uses: chetan/git-restore-mtime-action@v1**
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: bkbrpark
          # Deploy Options
          **fetch-depth: 0**
          REMOTE_PATH: "wp-content/"
          PHP_LINT: TRUE
          CACHE_CLEAR: TRUE

**Comment by jacksonwp** [comment]
@JStantonWordPress Not quite - `fetch-depth` is an input for the `actions/checkout@v3` workflow. So you would revise the beginning of your steps like this:

```
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Restore Timestamps
        uses: chetan/git-restore-mtime-action@v1

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
```
