### ISSUE TITLE
Files not deleted from remote server when deleted in repo

### ISSUE THREAD

**Issue by ravewebdev** [wpengine/github-action-wpe-site-deploy#108]
**Describe the bug**
The workflow does not delete files/folders from the server when they're deleted in the repo. This has caused builds to fail when a folder containing PHP classes was replaced with a renamed folder in the repo, with the error "PHP Fatal error:  Cannot declare class..." as it detected duplicate classes, despite the fact that in the repo the classes were actually unique. To fix the issue, we had to SFTP into the server and manually delete the old files. This should not be necessary.

### To reproduce
1. Add new file, commit and push to remote.
2. Delete that file, commit and push to remote.

The file will be deleted from the repo but _not_ from the server.

deploy workflow for reference:

```
name: Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
          git fetch --prune --unshallow

    - name: GitHub Action for WP Engine Git Deployment
      uses: wpengine/github-action-wpe-site-deploy@v3
      env:
        WPE_ENV: '<dev-install>'
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
```

### Expected behavior
Files deleted from the repo should be deleted from the server as well.

### Version information
- Action version: 3.2.6
- Git version: 2.45.2
- WordPress version: 6.6.2
- Operating system: MacOS Sequoia 15.0.1

**Comment by apmatthews** [comment]
Hi @ravewebdev 👋🏻

Correct, the action defaults to a non-destructive deploy. This is the intended behavior. If you'd like to make your deploy destructive, please check out [the `FLAGS` deploy option](https://github.com/wpengine/github-action-wpe-site-deploy?tab=readme-ov-file#deploy-options) for information on using the `--delete` rsync flag.

**Comment by groenroos** [comment]
Please take care to note that the `--delete` flag will destroy everything relative to `REMOTE_PATH`, not just files related to your GitHub repo. It will not take `.gitignore` or WP Engine's built-in exclusions into account.

So for instance, you do not want to use this in a situation where your repo is structured to represent the WP root (rather than a specific plugin or theme folder):

```yaml
- name: GitHub Action Deploy to WP Engine
  uses: wpengine/github-action-wpe-site-deploy@v3
  with:
    WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
    WPE_ENV: <your_install_name_here>
    SRC_PATH: "dist/"
    REMOTE_PATH: "/"
    FLAGS: -azvr --inplace --delete
```

The above configuration will delete all of WordPress from your remote, including user uploads.

**Comment by ravewebdev** [comment]
@groenroos thanks for noting that. We discovered that already when testing (which is why we intentionally spun up a new testing site to avoid breaking anything active), so it's good to know that wasn't a bug/error on our part.

@apmatthews given that the `--delete` flag wipes out the entire root directory, _not_ just the files deleted via git, what are our options? Is there a way to configure the workflow to _only_ delete files we indicate should be deleted? Or do we really have to SFTP into the site every time we want to delete a file?

**Comment by kingkool68** [comment]
I got around this by syncing different directories in different steps instead of trying to sync the entire repo in one step. My GitHub action looks like this:

```
name: Deploy to environment by branch
on:
  push:
    branches:
     - main
     - wpengine-staging
     - wpengine-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Define variables used by all steps
      FLAGS: -azvr --inplace --delete
      WP_ENV: "none"
    steps:
    - name: Set WP_ENV variable based on branch
      run: |
        if [[ $GITHUB_REF_NAME == 'main' ]]; then
          echo "WP_ENV=prod" >> $GITHUB_ENV
        elif [[ $GITHUB_REF_NAME == 'wpengine-staging' ]]; then
          echo "WP_ENV=staging" >> $GITHUB_ENV
        elif [[ $GITHUB_REF_NAME == 'wpengine-dev' ]]; then
          echo "WP_ENV=dev" >> $GITHUB_ENV
        fi
    - name: What is $WP_ENV?
      run: echo ${{env.WP_ENV}}

    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Deploy theme
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        WPE_ENV: ${{env.WP_ENV}}
        FLAGS: ${{env.FLAGS}}
        SRC_PATH: "wp-content/themes/my-theme/"
        REMOTE_PATH: "wp-content/themes/my-theme/"
        CACHE_CLEAR: TRUE

    - name: Deploy custom plugin
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        WPE_ENV: ${{env.WP_ENV}}
        FLAGS: ${{env.FLAGS}}
        SRC_PATH: "wp-content/plugins/my-plugin/"
        REMOTE_PATH: "wp-content/plugins/my-plugin"
        CACHE_CLEAR: TRUE
```

If you use this make sure to update the `WP_ENV=xxx` part in the `Set WP_ENV variable based on branch` step to match the name of your WP Engine environments.
