### ISSUE TITLE
Unknown filter rule: `':-' When trying to add filter flag to FLAGS

### ISSUE THREAD

**Issue by ops-andy** [wpengine/github-action-wpe-site-deploy#80]
**Describe the bug**
We're trying to set up a better workflow where files that are not part of the deployment, not excluded in rsync, and not listed in our .gitignore file are deleted.  Found what seemed to be a pretty decent option. However it causes an error when the pipeline is ran.
Error:   
```
Unknown filter rule: `':-'
rsync error: syntax or usage error (code 1) at exclude.c(1212) [client=3.2.7]
```

### To reproduce
Create a pipeline in Bitbucket using the WPengine pipe:
```
            - pipe: wpengine/wpe-site-deploy:v1
              variables:
                WPE_SSHG_KEY_PRIVATE: $WPE_SSHG_KEY_PRIVATE
                WPE_ENV: ENVNAME
                FLAGS: --include='**.gitignore' --exclude='/.git' --filter='\:- .gitignore' --delete-after
```

### Expected behavior
Expect for the repo to be deployed to the respective environment and all files not explicitly excluded nor listed in our .gitignore are deleted. 

### Build Output & Screenshots
Related Output from the pipeline:
```
Authenticated to [env.ssh.wpengine.net](http://env.ssh.wpengine.net/) ([IP]:22) using "publickey".
debug1: setting up multiplex master socket
debug1: channel 0: new mux listener [/root/.ssh/ctl/c84fdf] (inactive timeout: 0)
debug1: forking to background
debug1: Entering interactive session.
debug1: pledge: id
!!! MULTIPLEX SSH CONNECTION ESTABLISHED !!!
Unknown filter rule: `':-'
rsync error: syntax or usage error (code 1) at exclude.c(1212) [client=3.2.7]
```

### Version information
- Action version: v1
- WordPress version: 6.4.2 

### Additional context
I'm up for other best practices to handle this if there is a known better way.
